### ISSUE TITLE
Scorecard Selection on Challenge Creation

### ISSUE THREAD

**Issue by rootelement** [appirio-tech/direct-app#146]
## Requirements
1. Add a "Description" to the scorecard object.
2. When you create a challenge, on the screen where you select your challenge type, there should be a dropdown of active scorecards for the selected challenge type, defaulting to the current default for that challenge type.
3. Next to, or beneath the dropdown for scorecards, the description should show up.  There should be a description of what the scorecard encompasses with a link underneath that to preview the scorecard.
## Questions
1. Does everyone who has access to direct to create a challenge have access to select/change scorecards?

**Comment by ajefts** [comment]
In progress:  https://www.topcoder.com/direct/contest/detail.action?projectId=30055620

**Comment by ajefts** [comment]
This is released.  Does not have the nice description of the scorecard you were hoping for...
