### ISSUE TITLE
Tasks - unable to lower prize

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/direct-app#163]
If you save a draft task, you can't lower the prize. I believe it's triggering validation since the registration phase is closed.  It's a rule we have for active challenges.

![image](https://cloud.githubusercontent.com/assets/3812270/21250158/16326d7e-c311-11e6-89a7-c31ea7f2e308.png)

**Comment by ajefts** [comment]
@skyhit Can you get this one fixed please?

**Comment by skyhit** [comment]
@ajefts  so for draft challenge, we are allowing to lower the prize, but not for others

**Comment by ajefts** [comment]
Right.  I think it's probably just checking if the reg phase has started/ended and ignoring the challenge status.  If we add the challenge status into the logic I think we'll be ok.

**Comment by skyhit** [comment]
@ajefts challenge launched - https://www.topcoder.com/direct/contest/detail?projectId=30055974

**Comment by skyhit** [comment]
@ajefts I didn't my own investigation, the main reason is for F2F challenge, when it is in draft challenge, we already close the registration phase, maybe we should change this update when activate challenge.

the current logic is if any phase is open or closed, you can not lower the prize.

**Comment by ajefts** [comment]
@skyhit Can we add an exception for the tasks? If it's a task then ignore that validation?

**Comment by skyhit** [comment]
@ajefts here raises another question.

When can we mark a challenge private? if only in draft status, I think we should close the registration phase when doing activation, instead of the current logic when we mark/unmark the private flag.

what do you think?

**Comment by ajefts** [comment]
I think that's a good idea. It actually simplifies it and avoids hitting some validation rules in OR when trying to update the challenge.

**Comment by skyhit** [comment]
so let's proceed? and we can still make the assign members logic, to add more members if the previous members can not complete.

**Comment by ajefts** [comment]
Yes, please.

**Comment by ajefts** [comment]
@skyhit Any update on this one?  It's becoming a pretty popular issue...

**Comment by skyhit** [comment]
@ajefts sorry for ignoring it a long time, I will work on it today
