### ISSUE TITLE
Allow user to easily launch task immediately

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/direct-app#164]
Currently, you have to schedule the task start time for a given hour.  For tasks, can we allow the user to launch it immediately?

**Comment by skyhit** [comment]
@ajefts when activating a task, we set actual start date and end date for registration phase, and close it, will it start the submission phase?

**Comment by ajefts** [comment]
Let's hold on this.  I think we're actually ok for now since you can set the start date to the current date (or earlier) for F2F
