### ISSUE TITLE
Remove reviewer payment if Internal Review is selected.

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/direct-app#167]

**Comment by skyhit** [comment]
@ajefts the is a general logic for all regards less of private or public challenge?  are we going to setup the review payment separately? as for F2F challenge, copilot put much more effort for reviewing actually.

**Comment by ajefts** [comment]
Ok. Skip this for now. Let me think through the logic some more.

**Comment by skyhit** [comment]
@ajefts I think this is fixed, check https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30056445

**Comment by ajefts** [comment]
ok, thanks.
