### ISSUE TITLE
Close task immediately

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/direct-app#171]
Provide a shortcut experience for a user to be able to accept and close a task immediately either as successfully "Completed" or "Cancelled".

1. If the submissions are in and the task owner wants to review them, then they should follow the normal review scorecard process and let the challenge workflow run as it normally would.

2. Provide an option in Direct to "Cancel Task"
   - Update the status of the challenge to "Cancelled - Client Request"

3. If the task is one in which a submission is not required (i.e. might be a deployment task or a task done off platform), then provide the following:
   - Button on the Direct challenge page that is labelled "Close Task"
   - When clicked, provide a dropdown list of registrants on the task. Also provide an option to    
   - The task owner can select the member they want to be the winner.
   - The system should submit a dummy submission file for the winner and close the submission phase.
   - Close the review phase with a score of 100 for the winner.

**Comment by skyhit** [comment]
@ajefts when there are more than one submission, how should we do for submissions? this seems also related to prizes setting.

**Comment by ajefts** [comment]
We should follow the rules of the challenge structure. So, if the task is completing as a success then we should require passing review(s). If we're failing it, then we can just mark it cancelled without completed reviews.   Let's start with that and then we can separately figure out if we want to be able to close a task to pay a member without a submission.

**Comment by skyhit** [comment]
@ajefts no, I mean if there are two assigned submitters, and we only set a prize, and we didn't resolve the review scorecards, how can we determine the winner, by simply clicking the `Complete` button?

**Comment by ajefts** [comment]
@skyhit I updated the requirements on this one. Let me know what you think.

**Comment by skyhit** [comment]
@ajefts looks good,I have drafted this challenge - https://www.topcoder.com/direct/contest/detail?projectId=30056015, please confirm to launch

**Comment by ajefts** [comment]
Looks good

**Comment by skyhit** [comment]
@ajefts ok, let's launch it
