### ISSUE TITLE
Registration phase logic for tasks

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/direct-app#173]
Please make sure the task registration phase logic isn't impacting other challenges.  I've seen 2 cases where the registration phase on active design challenges have changed after confirming checkpoint winners.

**Comment by ajefts** [comment]
@skyhit Can you put this high on your list?

**Comment by skyhit** [comment]
@ajefts sure, let me check

**Comment by skyhit** [comment]
@ajefts for confirming checkpoint winners, you mean the registration phase is closed? looks like this is expected. 

see https://github.com/appirio-tech/direct-app/blob/dev/services/contest_service_facade/src/java/main/com/topcoder/service/facade/contest/ejb/ContestServiceFacadeBean.java#L8595-L8763

**Comment by ajefts** [comment]
But is it changing the dates now too? I noticed the phase dates were weird.

**Comment by skyhit** [comment]
@ajefts this 

check this 

https://github.com/appirio-tech/direct-app/blob/dev/services/contest_service_facade/src/java/main/com/topcoder/service/facade/contest/ejb/ContestServiceFacadeBean.java#L8630-L8647

```
                for (com.topcoder.project.phases.Phase phase : projectPhases.getAllPhases()) {
                    if (phase.getPhaseType().getId() == PhaseType.REGISTRATION_PHASE.getId()) {
                        if (phase.getPhaseStatus().getId() == PhaseStatus.OPEN.getId()) {
                            isRegClosed = false;
                            phase.setPhaseStatus(PhaseStatus.CLOSED);
                            phase.setScheduledEndDate(currentDate);
                            phase.setActualEndDate(currentDate);
                        }
                    }
                    if (phase.getPhaseType().getId() == PhaseType.SUBMISSION_PHASE.getId()) {
                        if (phase.getPhaseStatus().getId() == PhaseStatus.OPEN.getId()) {
                            isSubClosed = false;
                            phase.setPhaseStatus(PhaseStatus.CLOSED);
                            phase.setScheduledEndDate(currentDate);
                            phase.setActualEndDate(currentDate);
                        }
                    }
                }
```

**Comment by ajefts** [comment]
@skyhit I'm looking at the audit records for one of the challenges.  It didn't close it.  It actually seemed to adjust the times. I'm not sure if it's related, but we'll need to keep an eye on other challenges.  In this one case I'm looking at, it appears the registration end date changes from 12/19 to 12/27 immediately before the checkpoint review phase closed (when the checkpoint review was submitted from Direct).


835236	Submission		2016-12-19 06:17:00.0	Update	2016-12-16 12:30:05.547	adroc
835241	Approval	2016-12-25 10:17:00.0	2016-12-30 10:17:00.0	Update	2016-12-16 12:30:05.547	adroc
835239	Screening	2016-12-19 06:17:00.0	2016-12-19 10:17:00.0	Update	2016-12-16 12:30:05.547	adroc
835240	Review	2016-12-19 10:17:00.0	2016-12-25 10:17:00.0	Update	2016-12-16 12:30:05.547	adroc
835234	Registration		2016-12-19 06:12:00.0	Update	2016-12-16 12:30:05.547	adroc
835234	Registration	2016-12-16 12:30:29.397	2016-12-27 00:12:00.0	Update	2016-12-16 12:30:29.475	AutoPilot
835238	Checkpoint Review		2016-12-16 12:32:13.199	Update	2016-12-16 12:32:13.289	AutoPilot

The order of those date columns is phase scheduled start, phase scheduled end, modified date.
