### ISSUE TITLE
Billing Account Management API

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/direct-app#180]
Create a service and API for managing Topcoder billing accounts.

- This should be a new microservice (/v3/billingaccount)
- There is some existing code in the v2 api (https://github.com/appirio-tech/tc-api/blob/master/actions/platform.js) that is not being used and was never fully tested.  We will be replacing that.
- The actions that the API needs to handle are:
   - Create a new billing account
   - Assign users to a billing account
   - Remove users from a billing account
   - Update a billing account (including name, dates, status)
   - Get all billing accounts (filter on status, customer, user, dates)
- Security and Permissions:
   - Admin users can create billing accounts, update billing accounts, assign users, remove users, view all billing accounts.
   - non-admin users can only see their own billing accounts

**Comment by ajefts** [comment]
@skyhit Want to take this one?

I'd like to try running several smaller challenges to get this built:

- swagger challenge to define the interface (we'll use this to review with our team before implementing it)
- test case development
- environment setup (CI/CD).  make sure it's easy for members to work on, configuration is all set for different environments, build processes are setup, etc.
- implementation

@dmessing Let me know if I'm missing anything specific in terms of the process to build API's that we want to start using.

**Comment by skyhit** [comment]
sure
ajefts <notifications@github.com>于2016年12月23日 周五上午4:20写道：

**Comment by skyhit** [comment]
spec creation challenge launched - https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30056101

**Comment by ajefts** [comment]
@parthshah Any thoughts on how to model the "Org" concept here?

Right now we have client --> billing account --> users

Challenges are associated to billing accounts, which is what allows us to roll challenges up to clients.  Is the org really the client?

**Comment by ajefts** [comment]
Next steps here are to run challenges for the mock, tests, and actual implementation.  

We'll add additional features after the first implementation.  First implementation will focus on current feature sets so we can get ourselves in a position to manage client and billing records without sfdc.

**Comment by skyhit** [comment]
@ajefts let's close this since we have separate repo for billing account apis?
