### ISSUE TITLE
Error page shown when trying to create project from right side-menu

### ISSUE THREAD

**Issue by aaabbott** [appirio-tech/direct-app#198]
## Description

When a user tries to create a project using the menu that is on the righthand side of of the screen, they are shown an JBoss error page.

```
HTTP Status 404 - There is no Action mapped for namespace [/] and action name [index] associated with context path [/direct].

type: Status report

message: There is no Action mapped for namespace [/] and action name [index] associated with context path [/direct].

description: The requested resource (There is no Action mapped for namespace [/] and action name [index] associated with context path [/direct].) is not available.
```

## Steps to Reproduce
1. In Direct, view all projects.
2. Expand righthand side menu and select "Start Project" link
3. Observe

## Screenshots
![image](https://cloud.githubusercontent.com/assets/6266701/21854261/1e61b220-d7e8-11e6-9f36-9f7ae2f2fd5f.png)

**Comment by ajefts** [comment]
@skyhit Can you take a look at this one please?  I'm guessing it's related to our struts upgrade.

**Comment by skyhit** [comment]
@ajefts yes, previously space is not raising problem, I think I reported before.

the url is looking like https://www.topcoder.com/direct/%20createNewProject.action

we need to remove the %20 in the formed url
