### ISSUE TITLE
Add/Remove Resources on Direct Project via API 

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/direct-app#199]

**Comment by skyhit** [comment]
@ajefts should we merge this first?

https://github.com/appirio-tech/tc-direct-project-service/pull/15

**Comment by ajefts** [comment]
Yes. Let's get this into dev and see how it works.

**Comment by skyhit** [comment]
@ajefts I see you merged the PR, should we close this one?

**Comment by ajefts** [comment]
not yet.  This is just in dev.
