### ISSUE TITLE
Thought About Separating out scorecard tool

### ISSUE THREAD

**Issue by skyhit** [appirio-tech/direct-app#208]
the scorecard tool is not changed for long, but the direct build is always building it, I was thinking to separate it out.

I am thinking about the following steps.

1. figure out if we can run scorecard tool separately, looks like it is only depending on informix database.

for this we can try out to use this docker image to run - https://hub.docker.com/r/onesysadmin/grails/tags/

2. if it can be run separately, update the code to redirect to the official login page for account login.

3. figure out way to create docker by using environment variables for database related configuration, if so, we can prebuild the image and adapt it to work with different environment. even for locally.

4. remove scorecard_tool from direct to build and run separately.

**Comment by skyhit** [comment]
@ajefts let me know your thought.

**Comment by ajefts** [comment]
@skyhit I like the idea of separating it to it's own app and putting it behind accounts.topcoder.com.

Go for it, but please keep this as lower priority.

**Comment by skyhit** [comment]
it is done
