### ISSUE TITLE
Unable to Edit Task Payment

### ISSUE THREAD

**Issue by rsial2** [appirio-tech/direct-app#214]
If you enter a task payment and forget to assign it to a member, you're unable to edit it later:
![image](https://cloud.githubusercontent.com/assets/5807576/22216810/280dcc00-e166-11e6-97cd-1f1e050882e4.png)

If you go into OR, you're unable to add a user there as well.

**Comment by ajefts** [comment]
@skyhit Let's get a fix in for this one please.

**Comment by ajefts** [comment]
fyi @rsial2 This one is fixed.

**Comment by rsial2** [comment]
@ajefts & @skyhit, not able to edit an existing task:
![image](https://cloud.githubusercontent.com/assets/5807576/22608062/6952e26e-ea20-11e6-9e4a-b415b7ac73de.png)

**Comment by rsial2** [comment]
can you reopen this ticket?

**Comment by skyhit** [comment]
@rsial2 what do you mean for an existing task, it is already closed?

**Comment by rsial2** [comment]
No the task was still open. No member was assigned when I created the ticket, and when I tried to edit the ticket after I created it, I was unable to add a value for "Assign Members"
