### ISSUE TITLE
Double payment fix

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/direct-app#215]
I believe that if you hit close multiple times, it stages multiple payments.

Let's prevent that action if the task has already been closed. We can also remove the button after the task has been closed.

**Comment by ajefts** [comment]
@skyhit This is one we need a quick fix for please.

**Comment by skyhit** [comment]
@ajefts wired, this payment is actually set by API, we clear it for each clicking?

**Comment by ajefts** [comment]
So, clicking Close more than once shouldn't be triggering any payments?  It's only AP that creates the payments?

What if AP closed the challenge, and then someone manually clicked the Close button?
