### ISSUE TITLE
Error with Registration dates when closing tasks

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/direct-app#218]
If you attempt to close a task in Direct and the registration scheduled and end dates are NOT in the future, the app errors complaining that the start date can't be greater than the end date.

The error gets raised on this call:  https://github.com/appirio-tech/direct-app/blob/master/services/contest_service_facade/src/java/main/com/topcoder/service/facade/contest/ejb/ContestServiceFacadeBean.java#L9158

And then triggers the validator in the Phase class:

Caused by: java.lang.IllegalArgumentException: scheduledEndDate can not before scheduledStartDate
	at com.topcoder.project.phases.ProjectPhaseHelper.checkDateNotBefore(ProjectPhaseHelper.java:79
I believe this happens if you create the task, but then don't activate/close it right away.  However, I think we should generically check this case when closing tasks.  We probably need to update the logic for setting the dates.  Maybe if the reg dates are already set, we should not attempt to update them.

**Comment by ajefts** [comment]
fyi @skyhit  Let's put some priority on this one please.

**Comment by skyhit** [comment]
@ajefts sure, I am on it

**Comment by skyhit** [comment]
@ajefts sure, mainly I think we should adjust the logic here - https://github.com/appirio-tech/direct-app/blob/master/services/contest_service_facade/src/java/main/com/topcoder/service/facade/contest/ejb/ContestServiceFacadeBean.java#L9134-L9174

**Comment by ajefts** [comment]
yes, I agree.  I don't think we should overwrite the scheduled dates for the phase if it's already complete.
