### ISSUE TITLE
Add challenge property for "product"

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/direct-app#219]
Add a property to the challenge model for "product_type".

**Comment by skyhit** [comment]
@ajefts this is a new field?  what is the purpose for this property? 

we just need to add a new field as a project property (challenge property)?

**Comment by ajefts** [comment]
Right, just add a new project info value. We're starting to sell TopCoder services as products when we work with customers. For example, a prototype is packaged as a product.  The product has pricing, game plan templates, etc. We will be creating a separate entity for the actual product and related config. This property will simply tell us if the challenge is related to a specific product.

**Comment by skyhit** [comment]
we can use this sql.

```
INSERT INTO 'informix'.project_info_type_lu(project_info_type_id,name,description,create_user,create_date,modify_user,modify_date) VALUES (83, 'Product Type', 'Product Type', 'System', CURRENT, 'System', CURRENT);
```

let me know if the `project_info_type_id` is unavailable.

**Comment by ajefts** [comment]
in dev, we have 83 set to "PreRegister Users".  Are we still using that?

**Comment by skyhit** [comment]
@ajefts no, it is not used anymore, please remove it, it is already updated in https://github.com/topcoder-platform/tc-database-scripts/blob/master/tcs_catalog/02_tcs_catalog_data_setup.sql

**Comment by ajefts** [comment]
@skyhit Was the api updated to be able to set and get this attribute?  Can we add it?

**Comment by skyhit** [comment]
@ajefts you want this be supported in direct app side or in challenge api?

**Comment by ajefts** [comment]
Both please. Let's add a field to direct only for TopCoder admins.

**Comment by skyhit** [comment]
@ajefts sure I can add this, just not sure the complete purpose for this change, as this is more lated to project scope.

**Comment by skyhit** [comment]
challenge launched - https://www.topcoder.com/direct/contest/detail?projectId=30056829
