### ISSUE TITLE
$0 prizes

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/direct-app#225]
Update the logic when creating challenges in Direct to allow $0 prizes.  This is used for fun challenges and a few other use cases.  We should also update the validation in OR to allow for this.

Currently, if you set $0 prize on a challenge in Direct it looks like it simply does not create the prize records in the DB, which causes errors when editing/closing challenges/tasks.

**Comment by skyhit** [comment]
@ajefts here is the challenge spec - https://www.topcoder.com/direct/contest/detail?projectId=30056660

and for online review, can we create a github repo similar as direct-app

**Comment by sah2ed** [comment]
@skyhit I'm working with Tony to move Online Review from svn to a GitHub repo.

**Comment by skyhit** [comment]
@sah2ed is it created?

**Comment by sah2ed** [comment]
Not yet but we plan to host it at https://github.com/topcoder-platform

**Comment by skyhit** [comment]
@sah2ed np

**Comment by ajefts** [comment]
@skyhit Looks good.  Please launch
