### ISSUE TITLE
Validation update for project name and description

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/direct-app#231]
The validation on the project name and description is a bit too strong.  We need to make it match the validation on the connect project name/description.  Connect allows any text, and just escapes js/html/etc.

**Comment by ajefts** [comment]
@skyhit Mind getting this one done?

**Comment by skyhit** [comment]
@ajefts sure, where can I see the validation on the connect project name and description?

**Comment by ajefts** [comment]
It allows any characters. It just makes sure to prevent any kind of injection.  Do we have some kind of filter that we can use for text fields?

**Comment by ajefts** [comment]
@skyhit Can you run something for this quickly?  We hit it pretty often when creating projects from Connect since the API calls fail...

fyi @fnisen @parthshah

**Comment by ajefts** [comment]
@skyhit Let's also make the description optional in the API

**Comment by skyhit** [comment]
@ajefts I will get this ready as quickly as I can

**Comment by fnisen** [comment]
Thanks @ajefts and @skyhit

**Comment by skyhit** [comment]
@ajefts I checked the implementation of API, the description can be optional, there is no strict validation for that

**Comment by skyhit** [comment]
@ajefts PR created, please merge,  test and release
