### ISSUE TITLE
Design challenge registration phase end date

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/direct-app#241]
Set the end date for registration to be equal to the end date of the checkpoint submission phase if the challenge is a design challenge.

**Comment by ajefts** [comment]
@skyhit Can you get this updated in Direct please?


fyi @adroc-tc

**Comment by skyhit** [comment]
@ajefts @adroc-tc ok, what if there is no checkpoint submission phase?

**Comment by adroc-tc** [comment]
1-Round challenge Registration is open the entire Submission Phase
2-Round Challenge Registration is only open during Checkpoint Phase

**Comment by skyhit** [comment]
challenge launched - https://www.topcoder.com/direct/contest/detail?projectId=30057097

**Comment by skyhit** [comment]
@ajefts @adroc-tc code change is ready - https://github.com/appirio-tech/direct-app/pull/242
