### ISSUE TITLE
First to Finish End Date

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/direct-app#246]
Update the config so that F2F is 10 days instead of 30.

**Comment by ajefts** [comment]
@skyhit Mind updating this one?

**Comment by skyhit** [comment]
@ajefts do we need to update for Design F2F?

**Comment by ajefts** [comment]
Yes, please.

**Comment by skyhit** [comment]
@ajefts please check https://github.com/appirio-tech/direct-app/pull/247

**Comment by skyhit** [comment]
closed
