### ISSUE TITLE
Billing Status should use the status field and end date

### ISSUE THREAD

**Issue by mcards13** [appirio-tech/direct-app#248]
Currently, if a billing account end dates is in the past, the billing account will not be displayed for usage inTC Direct.

There is also a status on the billing account itself in the time_oltp project table.    The status should be used as well.

If the billing account status = 0, the billing account should be inactive and not allowed to be used.  This indicates the billing account is inactive despite what the start and end dates are set to.

In this scenario below, TC Direct should not allow a user to use the billing account.   
Billing Account Status = 0
End Date = something greater than current date

**Comment by skyhit** [comment]
@mcards13 @ajefts which page is it related to?

**Comment by ajefts** [comment]
@skyhit This is when you Edit a project and select a billing account for the project.

**Comment by skyhit** [comment]
@ajefts the table is a bit confusing 

```
create table 'informix'.project (
    project_id INT not null,
    company_id INT not null,
    name VARCHAR(64) not null,
    active SMALLINT not null,
    sales_tax DECIMAL(8,3) not null,
    po_box_number VARCHAR(20) not null,
    payment_terms_id INT not null,
    description VARCHAR(255),
    start_date DATETIME YEAR TO SECOND not null,
    end_date DATETIME YEAR TO SECOND not null,
    project_status_id INTEGER,
    client_id INTEGER,
    parent_project_id INTEGER,
    is_deleted SMALLINT DEFAULT 0,
    creation_date DATETIME YEAR TO SECOND not null,
    creation_user VARCHAR(64) not null,
    modification_date DATETIME YEAR TO SECOND not null,
    modification_user VARCHAR(64) not null,
    is_manual_prize_setting SMALLINT DEFAULT 0,
    budget DECIMAL(10,3),
    subscription_number  VARCHAR(64),
    billable boolean default 'f'
)
extent size 32 next size 32
lock mode row;
```

which field is usef for status, I can see `active`, `project_status_id`, `is_deleted` is used for this purpose.

**Comment by ajefts** [comment]
It's the active column.  0 or 1.
