### ISSUE TITLE
Task assignment to group member

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/direct-app#271]
If I create a challenge and assign group(s), then the task assignee should be limited to members in the groups.  ideally, let's change the control to a type ahead dropdown.

**Comment by skyhit** [comment]
challenge launched https://www.topcoder.com/direct/contest/detail?projectId=30058351

**Comment by skyhit** [comment]
will use api like https://api.topcoder.com/v3/members/_search/?query=MEMBER_SEARCH&handle=fire&offset=0&limit=10

**Comment by skyhit** [comment]
@ajefts the type ahead dropdown is already supported, but in order to filtering by groups, is that mean, if the groupIds present, we should use the groups APIs instead, is there a endpoint for group users, but I think the is limited to be access for authorized user?

**Comment by ajefts** [comment]
yes, you need to be authorized to access it.  Are we able to do this now?

**Comment by ajefts** [comment]
@skyhit What do we need to move forward with this one?

**Comment by skyhit** [comment]
@ajefts can we decide the flow? 
1. if no group select, it will use the general user suggestion?
2. if a group selected, it will call the group users api?
3. what if no group selected, and chosen some users, then select a group, should we clean up the previou user selections, which may not in the select group.

**Comment by ajefts** [comment]
Yes. The flow you describe is correct. For 3, we should alert the user that if they set the new group then the assignee will be removed.

**Comment by skyhit** [comment]
@ajefts another problem, since the group members api, only querying for one group a time, so we need to call several times if we defines multiple groups for a challenge, also there is no logic for suggest based on the entered user info.  how should we deal with this case

**Comment by huangqun** [comment]
@skyhit so do you need further updates made to the groups api? If so could you provide specific details?

**Comment by skyhit** [comment]
@ajefts @huangqun here is my undersanding, 

1. for the get members by group api, it is not returning any info about handle, but user id, so in order to enrich it, special processing is required for in direct app, before supporting type ahead.
2. for the get members by group api, we need to call several time and union the members in direct app.

that is said, we need to provide a sepcial endpoint in direct app by wrapping arround the groups API.

is that fine?

**Comment by ajefts** [comment]
@skyhit What exactly will the endpoint you're suggesting do?  Are you thinking we should have that as part of the group service?

**Comment by skyhit** [comment]
closing as it is implemented.
