### ISSUE TITLE
Remove validation that prevents lowering prizes

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/direct-app#285]
Currently, Direct does not allow you to lower a prize on a challenge.  Let's allow it for challenges that have not launched yet. i.e. if it's a draft or its active but registration has not yet started.

**Comment by skyhit** [comment]
@ajefts challenge launched - https://www.topcoder.com/direct/contest/detail?projectId=30058442

**Comment by skyhit** [comment]
@ajefts changes commited in dev branch

**Comment by skyhit** [comment]
@ajefts this is completed.
