### ISSUE TITLE
Can't Save Checkpoints Anymore

### ISSUE THREAD

**Issue by mahestro** [appirio-tech/direct-app#286]
Hey old pal @skyhit :)

Someone told me to poke you for help (blame on Tony). I have several challenges where the checkpoint phase has to be done manually in OR because it’s not working in Direct anymore. When you are in the checkpoint confirmation screen and click on « save checkpoint », it throws a strange message « * Enter your feedback above » in spite of having already entered text.

http://take.ms/0F1PW

I detected this yesterday and now there has been three challenges affected.

Do you think there is a way to fix this? Processing checkpoint submission through OR consumes lots of time. I’d appreciate if you guys could do something for us here.

Let me know if you need more information from my end.

Thanks in advance,
Luis

**Comment by skyhit** [comment]
@mahestro we need to have a way to reproduce it, is there any easy way?

**Comment by mahestro** [comment]
@skyhit, I understand. Today, in about 2h I'll be processing another checkpoint feedback for a challenge. Once I load the information in Direct I can let you hit the confirm button so you can reproduce the error. Would that work?

**Comment by skyhit** [comment]
@ajefts worked with @mahestro to reproduce it, looks like it is a backend problem to save general feedback, can you check the logs to see what happens?
