### ISSUE TITLE
Challenges I Created Page Not Working

### ISSUE THREAD

**Issue by mahestro** [appirio-tech/direct-app#288]
Hey guys,

I used this page a lot and it hasn't been working for quite long. Is it possible/easy to bring it back?

- http://take.ms/jGOhM
- http://take.ms/PEvtZ

Let me know if you need anything from me to help reproducing the error.

**Comment by skyhit** [comment]
@mahestro  @ajefts just discussed with me about this, are you reporting to him?

**Comment by mahestro** [comment]
No, I just got excited of the fact that I could report Direct issues and reported this. I didn't mention it to Tony.
