### ISSUE TITLE
Check group permissions when adding challenge resources

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/direct-app#295]
When you add resources to a challenge that is restricted to a group, it doesn't currently let you do it since the legacy apps (OR, /tc) check user_group_xref instead of the new group api.  We need to update the apps to check groups against the new api.

So far, I've noticed this when adding resources via OR and also on the reviewer registration pages.

**Comment by ajefts** [comment]
@skyhit I'd like to get moving on this one.  Can you run some challenges to make sure we're validating group membership correctly in OR?

**Comment by skyhit** [comment]
@ajefts his is related to update for OR, am I right?

**Comment by ajefts** [comment]
That's correct.

**Comment by skyhit** [comment]
@ajefts please confirm to launch - https://www.topcoder.com/direct/contest/detail?projectId=30059281

**Comment by ajefts** [comment]
confirmed.

**Comment by skyhit** [comment]
this is completed.
