### ISSUE TITLE
scorecard drop down on direct

### ISSUE THREAD

**Issue by dmessing** [appirio-tech/direct-app#307]
Looks like when you edit a challenge you can't scroll in the scorecard drop down.   I believe the top of the dropdown falls under the Z level of the top navigation bar. 

One small fix might be to deactivate a bunch of scorecards we have over 50 review scorecards currently.  Maybe @rootelement can help give us a list to be deactivated?  If we deactivate a bunch we can postpone the bug fix if need be.

**Comment by dmessing** [comment]
Here is a list of all active scorecards we can update this list

https://docs.google.com/spreadsheets/d/1v6xHJa_rXY1gxRPsi7Q9G7dueOIVQ8TtwF1AHlkAiuM/edit#gid=0

**Comment by skyhit** [comment]
@dmessing should we fix the list or the dropdown?

**Comment by ajefts** [comment]
@skyhit Let's fix the dropdown.  We can also clean up the data, but the dropdown should work either way.

**Comment by rootelement** [comment]
@ajefts I don't understand. This is closed? Was it fixed? Was there a Pull Request? Usually you link the Pull Request to the issue.. "fixes # 307" (no space) and it close the issue automatically.

**Comment by skyhit** [comment]
@rootelement it is fixed by #308 , do you still see the problem?

**Comment by rootelement** [comment]
Now I see it since the PR #308 was edited. Thanks @skyhit. I will test it out.
