### ISSUE TITLE
Style need to match

### ISSUE THREAD

**Issue by sushilshinde** [appirio-tech/direct-app#350]
Testing - https://www.topcoder-dev.com/direct/launch/home

Dropdown style needs to match to other dropdowns

![topcoder direct](https://user-images.githubusercontent.com/683231/34478224-cabe8b56-efc5-11e7-98ce-762f600a9735.png)

FYI... @ajefts

**Comment by skyhit** [comment]
@sushilshinde @ajefts there is a deployment issue for direct app, I think the static files are not deployed

**Comment by skyhit** [comment]
@sushilshinde the problem should be fixed in dev, please check

**Comment by sushilshinde** [comment]
@skyhit yes it is fixed, so closing
