### ISSUE TITLE
Clicking on Project Name Game Plan Gantt Chart Throws a Server Error

### ISSUE THREAD

**Issue by RiteshTC** [appirio-tech/direct-app#364]
Steps 
1. Create a new project. Add yourself to the project with full privileges. Do not create any challenge in the project
2. Click on Menu Item Game Plan
3. Click Game Plan Gannt
4. Click on the Project Name on Gantt Chart.
5. A server side error page is displayed 
HTTP Status 404 - There is no Action mapped for namespace [/] and action name [erview] associated with context path [/direct].
<img width="771" alt="click" src="https://user-images.githubusercontent.com/5771673/36034756-18434cda-0ddb-11e8-806b-e885b4fb9498.png">
<img width="1440" alt="error" src="https://user-images.githubusercontent.com/5771673/36034759-1a22db56-0ddb-11e8-91b9-7a7a2cd152f9.png">

**Comment by ajefts** [comment]
@skyhit This isn't critical, but next time we do a Direct update can you please fix this one?  Thanks.

**Comment by skyhit** [comment]
@ajefts ok, I will check

**Comment by skyhit** [comment]
@RiteshTC the issue is fixed in dev branch, and you can verify in dev environment.
