### ISSUE TITLE
Assigning a User to a private Task raises an error

### ISSUE THREAD

**Issue by RiteshTC** [appirio-tech/direct-app#365]
The following error message is received when assigning Private Task to a member.
"Warning:" 
"These members fail to register" 
"<handle> - Can't register this user"

**Comment by skyhit** [comment]
@RiteshTC can you provide the detail steps?  we used the private task func a lot, but never see this problem

**Comment by RiteshTC** [comment]
Occurred on Saturday, 2 persons reported the same error.
There is no extra ordinary steps, just the same creating a challenge and assigning it to the user.

**Comment by skyhit** [comment]
I created this task - https://www.topcoder.com/direct/contest/detail?projectId=30062908 without any problem.

the assignment is related to when creating of the private task, or editing the private task?

**Comment by RiteshTC** [comment]
It was reproducible both during creation and edition. 
I think the issue might be  related to temporary glitch in  Elastic Search in Production.
Do you know, what might have caused this ?

**Comment by skyhit** [comment]
@RiteshTC for challenge creation or editing it is not working with ElasticSearch in Production at all.

is there any more information to be reproduced?

**Comment by RiteshTC** [comment]
Closing the case, as no other user has reported the issue. The cause of issue is still unknown.
