### ISSUE TITLE
Change "Cockpit" to "Direct" in Email Template  

### ISSUE THREAD

**Issue by RiteshTC** [appirio-tech/direct-app#366]
Change the text from Cockpit to Direct in the email Template that goes out when challenge phases are completed. 

<img width="660" alt="issue" src="https://user-images.githubusercontent.com/5771673/36135045-8ae8738e-10ae-11e8-8b4c-8eed5853f3c3.png">

**Comment by skyhit** [comment]
@RiteshTC this is related to Online Review system

**Comment by RiteshTC** [comment]
@skyhit can you please move it to the correct repo or provide me the url for the repo ?

**Comment by skyhit** [comment]
@RiteshTC similar like this - https://github.com/topcoder-platform/tc-online-review/blob/dev/conf/templates/iterative_review/end.txt, may be  we used a updated version in production.

**Comment by RiteshTC** [comment]
Thanks @skyhit . I have created a new issue to track
https://github.com/topcoder-platform/tc-online-review/issues/16
