### ISSUE TITLE
Remove VM Management

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/direct-app#371]
Remove the VM Management features from Direct.

**Comment by skyhit** [comment]
@ajefts a challenge for this?  should DB cleanup be included?

**Comment by skyhit** [comment]
@ajefts draft challenge spec - https://www.topcoder.com/direct/contest/detail?projectId=30063518

**Comment by ajefts** [comment]
Yes, a challenge is fine. You can leave the DB tables in place.

**Comment by skyhit** [comment]
done
