### ISSUE TITLE
post mortem phase for code challenges

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/direct-app#380]
Add the post mortem phase for code challenges.  I don't think we have this enabled currently.

**Comment by ajefts** [comment]
@skyhit Could you take this one?

**Comment by skyhit** [comment]
@ajefts sure

**Comment by skyhit** [comment]
@ajefts an F2F challenge is launched for this - https://www.topcoder.com/direct/contest/detail?projectId=30063934

**Comment by skyhit** [comment]
@ajefts code change is created - https://github.com/appirio-tech/direct-app/pull/381

we do specific logic for Code and F2F challenge type, but this is generally setup at billing account level
