### ISSUE TITLE
Add effort hours field

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/direct-app#383]
As a user creating/editing a challenge for a topgear group (any group under "Wipro All", including the parent) is able to set a field that captures the # of "Effort Hours".  This field should be labeled "Effort Hours Estimate".  Let's add it to the first page right below the groups dropdown.

![image](https://user-images.githubusercontent.com/3812270/38748469-312d111e-3f1c-11e8-9cc1-7fe4353d9e28.png)

**Comment by skyhit** [comment]
@ajefts this field would be generally required for any group? or specific to some group only?

**Comment by skyhit** [comment]
@ajefts if so, how to define the related control? any idea?

**Comment by ajefts** [comment]
@skyhit let's make it configurable based on client ID's for now.  i.e. I can configure 1 or more client IDs and when I create a challenge, the Effort Hours field will be available if the billing account rolls up to any of the client IDs

**Comment by skyhit** [comment]
@ajefts you mean to add a field in client table ?

**Comment by ajefts** [comment]
I don't have a strong preference on where we put the config, as long as it's something we can change without updating code.  

Do we have other config values stored someplace that we could leverage?

**Comment by skyhit** [comment]
@ajefts this should be closed, right?
