### ISSUE TITLE
Update Design Policies

### ISSUE THREAD

**Issue by trevorgerring** [appirio-tech/direct-app#409]
I have updated the design policies for Stock Artwork and Fonts. I've also split out "Icons" as a separate policy. 

**Stock Artwork**
https://docs.google.com/document/d/19LhtDa79ffnT2YfCF4pZvyMNYIlDnOgAXdiv3tt4ZxQ/edit?usp=sharing

**Fonts**
https://docs.google.com/document/d/16IVaJOqxynF-ZVQGNDS_VZ3WEQleWcSWP7ZGdRx5GHI/edit?usp=sharing

**Icons** (See #410 for "step 2" of having an Icons Policy)
https://docs.google.com/document/d/1qQOjvrROm-KVxrAaBizX0ss2nFOsbjn33n1LO8I87bg/edit?usp=sharing

Is there any way to version control these on the site? Adding a version number and "updated on 05/16/2018" information?

**Comment by trevorgerring** [comment]
@ajefts Any updates here?

**Comment by trevorgerring** [comment]
@ajefts Is this ever going to get updated? I'm just looking for a simple text change and has been sitting for months. We're telling the members of these updates and there is nothing to point them to

**Comment by ajefts** [comment]
https://help.topcoder.com/hc/en-us/sections/203967808-Design-Copyright-Font-and-Icon-Policies

Help center content updates for stock art and fonts.  Icon policy added to help center.
