### ISSUE TITLE
Completed challenges with expired billing account are not visible in Direct 

### ISSUE THREAD

**Issue by JayaDhaka** [appirio-tech/direct-app#415]
User can't access completed challenges in Direct because of the expired billing account. Please check and resolve it.

Completed project link: https://www.topcoder.com/direct/contest/detail.action?projectId=30060520 
Expired billing account link: https://topcoder.my.salesforce.com/a0U4100000288lV 

[projectexception.txt](https://github.com/appirio-tech/direct-app/files/2016294/projectexception.txt)

@skyhit @ajefts

**Comment by ajefts** [comment]
This  happens when no billing account is set on the project too.

**Comment by ajefts** [comment]
@skyhit Can you get us a fix for this one?  It seems to be introduced pretty recently.

**Comment by skyhit** [comment]
@ajefts yes, introduced by the effort hours feature. providing a fix now.
