### ISSUE TITLE
Change a field text on https://www.topcoder.com/direct/launch/home.action

### ISSUE THREAD

**Issue by JayaDhaka** [appirio-tech/direct-app#419]
Please change the text highlighted in attached screenshot from " Estimated Effort hours" to "Estimated Effort (in Equated offshore hours=onsite hours*6+ offshore hours)" for Topgear challenges only.

![inkedimage_li](https://user-images.githubusercontent.com/34749364/40478386-8edac4ea-5f66-11e8-8bf3-95fac4334d54.jpg)

@skyhit @ajefts

**Comment by skyhit** [comment]
Closed by #420

**Comment by ajefts** [comment]
Per the description, please update the label to "Estimated Effort".  Thanks.
