### ISSUE TITLE
Scorecard is reset when contest is activated

### ISSUE THREAD

**Issue by JayaDhaka** [appirio-tech/direct-app#421]
A user has noticed that if the default scorecard is changed to other like Data Science Subjective for a contest (code, prototype) and when the contest is activated, the scorecard appears to reset to the default.

Take this contest as example - https://software.topcoder.com/review/actions/ViewProjectDetails?method=viewProjectDetails&pid=30065701

Please check and resolve.

@skyhit @ajefts

**Comment by skyhit** [comment]
@JayaDhaka so the reproduce steps is like

1. Create a Draft challenge in direct app
2. make changes to the scorecard in online review
3. activate the challenge in Direct app
4. notice the default scorecard is changed, 

right?

**Comment by callmekatootie** [comment]
@skyhit That is correct.

If there are logs, then you can check out this contest for which I remember changing the scorecard to Data Science Subjective - https://software.topcoder.com/review/actions/ViewProjectDetails?pid=30065701 but it got reset to the default one

**Comment by skyhit** [comment]
@JayaDhaka F2F challenge launched for this  - https://www.topcoder.com/direct/contest/detail?projectId=30065876

**Comment by gurmeetb** [comment]
>> make changes to the scorecard in online review

Could you guide how do I open OR page ? Is it part of Direct App ?

**Comment by skyhit** [comment]
@gurmeetb no, online review is separated application see https://github.com/appirio-tech/tc-common-tutorials/tree/master/docker/online_review#verification

**Comment by callmekatootie** [comment]
@gurmeetb You are already familiar with OR - Online Review. It's the same page where you file your appeals. The Url is https://software.topcoder.com

**Comment by JayaDhaka** [comment]
@callmekatootie I would suggest you to follow the current logic that is to refresh the Direct page after making changes in OR.
