### ISSUE TITLE
Can not set boolean field Enable Effort Hours  to null value

### ISSUE THREAD

**Issue by RiteshTC** [appirio-tech/direct-app#428]
Receiving this error, when trying to associate a new/ existing billing account with any existing project in Direct.

Can not set boolean field com.topcoder.clients.model.Client.enableEffortHours to null value
The error causes the error message "Failed to get Client for Project".
![capture](https://user-images.githubusercontent.com/5771673/41495324-1b13965c-7142-11e8-9c1a-ca0c5bca0113.PNG)

cc @ajefts

**Comment by skyhit** [comment]
@RiteshTC the problem should be fixed, @ajefts need to push to prod, if you tested good in dev enviroment.
