### ISSUE TITLE
Member is not able to add any handle to project permissions in Direct

### ISSUE THREAD

**Issue by JayaDhaka** [appirio-tech/direct-app#439]
Our member (ahirve) is not able to add any handle like "Geejo" to the project permissions and also not able to assign any handle to any challenge of the project.
Direct project link: https://www.topcoder.com/direct/projectOverview.action?formData.projectId=17905
Please check and resolve.

![image 3](https://user-images.githubusercontent.com/34749364/42155890-3c565968-7e07-11e8-981c-fb084562aa8e.png)
 
Console error:

![image 4](https://user-images.githubusercontent.com/34749364/42160894-8069eade-7e16-11e8-8082-575251e517dd.png)

error message: 
{  
   "id":"-24c9b153:1645748200f:17bb",
   "result":{  
      "success":true,
      "status":401,
      "metadata":null,
      "content":"Valid credentials are required to access this resource."
   },
   "version":"v3"
}
@skyhit

**Comment by ajefts** [comment]
@cwdcwd @skyhit we need a quick patch for this one.  I don't see the suggest call getting made with a token.  I believe that is the issue.  Can we get this patched asap?

**Comment by cwdcwd** [comment]
@skyhit pls add in the user's JWT to the `Authorization` header on this call

**Comment by skyhit** [comment]
@cwdcwd @ajefts I am on it

**Comment by skyhit** [comment]
fixed, code in dev branch
