### ISSUE TITLE
Not able to add my handle jaya.dhaka to the Direct project

### ISSUE THREAD

**Issue by JayaDhaka** [appirio-tech/direct-app#446]
I am getting this error " Server error occurred. Please try the operation later" while adding my handle to the below Direct project. 

Direct project link is : https://www.topcoder.com/direct/editProject.action?formData.projectId=17526#permissionsNotifications 

![image 9](https://user-images.githubusercontent.com/34749364/42378276-607865b2-8144-11e8-98e2-187254d99c0a.png)

Error screenshot:
![image 8](https://user-images.githubusercontent.com/34749364/42378289-6bb3aa68-8144-11e8-8271-d4f10de0debc.png)

@skyhit Please check and fix the issue.

**Comment by ajefts** [comment]
@skyhit Here is the log:

11:09:42,867 ERROR [STDERR] java.lang.NullPointerException
11:09:42,867 ERROR [STDERR] 	at com.topcoder.direct.services.view.action.project.edit.SaveCockpitProjectSettingAction.saveProjectPermissionsAndNotifications(SaveCockpitProjectSettingAction.java:735)
11:09:42,867 ERROR [STDERR] 	at sun.reflect.GeneratedMethodAccessor1886.invoke(Unknown Source)
11:09:42,867 ERROR [STDERR] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
11:09:42,867 ERROR [STDERR] 	at java.lang.reflect.Method.invoke(Method.java:601)
11:09:42,867 ERROR [STDERR] 	at ognl.OgnlRuntime.invokeMethod(OgnlRuntime.java:899)
11:09:42,867 ERROR [STDERR] 	at ognl.OgnlRuntime.callAppropriateMethod(OgnlRuntime.java:1544)
11:09:42,867 ERROR [STDERR] 	at ognl.ObjectMethodAccessor.callMethod(ObjectMethodAccessor.java:68)
11:09:42,867 ERROR [STDERR] 	at com.opensymphony.xwork2.ognl.accessor.XWorkMethodAccessor.callMethodWithDebugInfo(XWorkMethodAccessor.java:96)
11:09:42,867 ERROR [STDERR] 	at com.opensymphony.xwork2.ognl.accessor.XWorkMethodAccessor.callMethod(XWorkMethodAccessor.java:88)
11:09:42,867 ERROR [STDERR] 	at ognl.OgnlRuntime.callMethod(OgnlRuntime.java:1620)
11:09:42,868 ERROR [STDERR] 	at ognl.ASTMethod.getValueBody(ASTMethod.java:91)
11:09:42,868 ERROR [STDERR] 	at ognl.SimpleNode.evaluateGetValueBody(SimpleNode.java:212)
11:09:42,868 ERROR [STDERR] 	at ognl.SimpleNode.getValue(SimpleNode.java:258)
11:09:42,868 ERROR [STDERR] 	at ognl.Ognl.getValue(Ognl.java:470)
11:09:42,868 ERROR [STDERR] 	at ognl.Ognl.getValue(Ognl.java:434)
11:09:42,868 ERROR [STDERR] 	at com.opensymphony.xwork2.ognl.OgnlUtil$3.execute(OgnlUtil.java:371)
11:09:42,868 ERROR [STDERR] 	at com.opensymphony.xwork2.ognl.OgnlUtil.compileAndExecuteMethod(OgnlUtil.java:423)
11:09:42,868 ERROR [STDERR] 	at com.opensymphony.xwork2.ognl.OgnlUtil.callMethod(OgnlUtil.java:369)
11:09:42,868 ERROR [STDERR] 	at com.opensymphony.xwork2.DefaultActionInvocation.invokeAction(DefaultActionInvocation.java:436)
11:09:42,868 ERROR [STDERR] 	at com.opensymphony.xwork2.DefaultActionInvocation.invokeActionOnly(DefaultActionInvocation.java:291)
11:09:42,868 ERROR [STDERR] 	at com.topcoder.direct.services.view.interceptor.ActionPreProcessor.intercept(ActionPreProcessor.java:154)
11:09:42,868 ERROR [STDERR] 	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:247)
11:09:42,868 ERROR [STDERR] 	at com.topcoder.direct.services.view.interceptor.ProjectAccessInterceptor.intercept(ProjectAccessInterceptor.java:197)
11:09:42,868 ERROR [STDERR] 	at com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:247)
11:09:42,868 ERROR [STDERR] 	at com.topcoder.direct.services.view.interceptors.AuthenticationInterceptor.intercept(AuthenticationInterceptor.java:388)

**Comment by cwdcwd** [comment]
@skyhit it looks like the project permissions coming back from the form are null and thus [this line](https://github.com/appirio-tech/direct-app/blob/a7753a7fb8736d17d2dc692d3dbf2d96843872b1/src/java/main/com/topcoder/direct/services/view/action/project/edit/SaveCockpitProjectSettingAction.java#L735) fails since the list is null?

**Comment by skyhit** [comment]
@cwdcwd @ajefts I will check

**Comment by ajefts** [comment]
resolved.
