### ISSUE TITLE
Update default terms

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/direct-app#455]
We are creating a new version of the standard TC terms.  The new terms ID is 21303.

We need to make sure Direct/Challenge API/etc. are updated to apply these terms by default for all new challenges as opposed to the current terms.

**Comment by ajefts** [comment]
@skyhit think  you could get this one done pretty quick for us?

**Comment by ajefts** [comment]
@skyhit I created a challenge in direct,  but I don't see the new terms getting applied to the challenge.

challenge id = 30053010

**Comment by skyhit** [comment]
@ajefts sorry, thought it was a simple change, but seems not,  will look into that today
