### ISSUE TITLE
Score Management menu redirects to login page.

### ISSUE THREAD

**Issue by NehaSharma02** [appirio-tech/direct-app#463]
Steps to reproduce issue
1. Open the link for Direct (https://www.topcoder.com/direct/enterpriseDashboard/activeContests.action)
2. Click on Admin menu.
3. Click on General sub menu, select Score Management.

This will redirect to Login page.
Please fix it asap.

@ajefts 
@RiteshTC

**Comment by RiteshTC** [comment]
Not a code issue,Restarting app server fixed the issue
