### ISSUE TITLE
Topgear update for effort capture

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/direct-app#469]
We want to capture efforts separately for onsite and offshore.  So instead of one field to capture efforts, we need 2 fields.

- Estimated Efforts : Offshore ( In Person Days)
- Estimated Efforts : Onsite ( in Person Days)

The fields must only be available to Topgear challenges (based on selecting the topgear billing account).  This is how it's currently implemented for the single field.

**Other relevant information**

- Let's hide the existing field (we don't want to lose the data) and add these 2 additional fields as new fields.
- Tool tips are not required.
- The user can enter data in 1 or both fields.  At least 1 field must be filled out.

**Comment by skyhit** [comment]
@ajefts for the existing data, we will still show it?

**Comment by ajefts** [comment]
No

**Comment by skyhit** [comment]
@ajefts assigned this to @deedee as private task, since he worked on the same logic before. hope we can get it ready soon

**Comment by ajefts** [comment]
ok, thanks

**Comment by skyhit** [comment]
@ajefts the implementation is ready - https://github.com/appirio-tech/direct-app/pull/472
