### ISSUE TITLE
Not able to Create new challenges in direct

### ISSUE THREAD

**Issue by sandhiyakavi** [appirio-tech/direct-app#564]
Description:

Not able to create new challenges in direct. Getting Server error "The form has already been processed or no token was supplied, please try again"

Design challenge:
![image (16)](https://user-images.githubusercontent.com/55895538/145370398-83332738-76cd-4e7e-8b08-cedc81f6fade.png)

**Comment by SathyaJayabal** [comment]
Also getting the same for MM challenge

**Comment by SathyaJayabal** [comment]
adding video

https://user-images.githubusercontent.com/58783823/145938061-ed82fabf-dcb0-48de-a4ce-d38920e7b0f2.mov

**Comment by sachin-maheshwari** [comment]
@lakshmiathreya as discussed issue is not related to jira-130.

**Comment by lakshmiathreya** [comment]
Direct is now functional ... regression testing has been resumed ...
